### ISSUE TITLE
[suggestion]hope Waterlogging/希望支持含水机制

### ISSUE THREAD

**Issue by h15588** [crabsatellite/hotBath#12]
hope hotbath's fluid are able to Waterlogging.i want to use non-cube block to decorate my bathhouse（my english is poor,sorry.)
能让热水澡这个mod的流体们支持含水机制吗秋梨膏，用楼梯装饰澡堂子发现温泉水不能灌到楼梯方块里头让我道心破碎了

**Comment by crabsatellite** [comment]
你好！我们已经花了一些时间在解决这个问题上了。自1.19版本以来，Forge无法像之前一样继承水的特性，导致入水音效、岩浆互动等效果全部失效。尽管我们在最新版本中尝试手动解决了一些音效逻辑，但对waterlogged的实现仍然较为复杂，因此我们正在研究其他模组成功的解决方案，以确保符合最佳实践。

目前，我们查看了多个成熟模组，包括Biomes O' Plenty、Ultimate Car等，发现即便是它们的液体（如血液桶、柴油）也无法实现含水或对应音效。这似乎是Minecraft更新带来的通病。为了解决这个问题，我们在Reddit和社区中发帖交流，如果您或其他开发者知道解决方法，或者游玩的过程中你发现有模组成功实现了类似逻辑，还请分享给我们。

https://www.reddit.com/r/MinecraftMod/comments/1gc1hyp/help_needed_with_custom_liquid_implementation_in/

如果最终确实需要从头实现相关逻辑，鉴于这一过程耗时较长，我们可能会优先将精力放在Neoforge的移植，以及加入基础的水和岩浆互动（如灭火）的更新上，以维持简单的水效果。

感谢你的反馈和对我们模组的支持！如果有机会，也欢迎你帮忙把这个问题发布到MC百科等平台，寻找更多解决方案。

**Comment by h15588** [comment]
https://modrinth.com/mod/fluidlogged/versions 这个mod或许对你们有帮助，此mod允许所有流体触发含水机制。我试过了，对热水澡mod的流体生效，我先拿这个mod顶着用会

**Comment by crabsatellite** [comment]
Hello, 看起来这个mod确实完美解决了这个问题，我们在1.20.1版本测试和热水澡mod是完全兼容的。那么本着不重复造轮子的原则，我们会推荐使用热水澡的玩家下载这个mod以获得完整体验，如果后面这个mod不更新了我们再考虑自己实现，谢谢你为社区做的贡献！

**Comment by h15588** [comment]
但是这个mod不支持混合端,arclight和mohist都崩,道心日常破碎。先给原mod和mohist都发个issue吧
