### ISSUE TITLE
【crash】hot bath mod cause sever crash  on 1.20.1 FORGE

### ISSUE THREAD

**Issue by sorataxi** [crabsatellite/hotBath#9]
here is the server crash report
forge version  47.3.6
[message.txt](https://github.com/user-attachments/files/16716830/message.txt)

**Comment by DoraWolf** [comment]
> here is the server crash report forge version 47.3.6 [message.txt](https://github.com/user-attachments/files/16716830/message.txt)

After our testing, this version is fine. Considering it conflicts with other mods, if you can identify which mod conflicts, perhaps we can try to resolve it

**Comment by DoraWolf** [comment]
> here is the server crash report forge version 47.3.6 [message.txt](https://github.com/user-attachments/files/16716830/message.txt)

This issue also depends on the code of other mods. Our mod is also used by ourselves and does not conflict with the mod on our server

**Comment by crabsatellite** [comment]
Thank you for the information! After looking into it, we found that Forge in certain versions, including 1.20.1, needs particle-related registrations to be clearly defined on the client side. In other older or newer versions, this isn’t necessary, which can cause issues during updates.

We’ve fixed the problem, and you can download the updated mod from [this link](https://www.curseforge.com/minecraft/mc-mods/hotbath/files/5668383). The server should now start correctly. We hope you enjoy the mod, and feel free to share any feedback—it really helps us improve.

**Comment by crabsatellite** [comment]
Update as of September 5, 2024: Some Forge versions may cause crashes. This issue's recent fix is in hotbath-1.20.1-1.2.0.jar and later versions. Testing on this issue is ongoing.
